import type { Metadata } from "next";
import "./globals.css";
import SocketProvider from "@/providers/socketProvider";
import { cookies } from "next/headers";
import ClientWrapper from "./client_wrapper";

export const metadata: Metadata = {
  title: "MealBridge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userId = cookieStore.get("userId")?.value || null;
  const token = cookieStore.get("token")?.value || null;
  console.log(userId);
  return (
    <html lang="en">
      <body>
        <ClientWrapper userId={userId} token={token}>
          <SocketProvider>
            Notification
            {children}
          </SocketProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
