import type { Metadata } from "next";
import "../globals.css";
import SocketProvider from "@/providers/socketProvider";
import { cookies } from "next/headers";
import ClientWrapper from "../client_wrapper";
import ReactQueryProvider from "@/providers/react_query_provider";
import { NotificationProvider } from "@/providers/notification_provider";
import { Header } from "@layout";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "MealBridge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const collectorId = cookieStore.get("collector_id")?.value || null;
  const token = cookieStore.get("collector_token")?.value || null;
  if (!collectorId || !token) {
    redirect("/signin");
  }
  return (
    <div className="max-w-[1500px] mx-auto">
      <ClientWrapper collectorId={collectorId} token={token}>
        <ReactQueryProvider>
          <NotificationProvider>
            <SocketProvider>
              <Header collectorId={collectorId} />
              {children}
            </SocketProvider>
          </NotificationProvider>
        </ReactQueryProvider>
      </ClientWrapper>
    </div>
  );
}
